/**
 * R2 Helper Utilities for YouTube Transcript Storage
 *
 * Simple utilities for uploading transcripts to R2 and generating public URLs.
 * Files are automatically cleaned up after 24 hours via R2 lifecycle rule.
 *
 * Lifecycle Rule: 'daily-cleanup' (configured via wrangler)
 * - Expires objects after 1 day
 * - No manual cleanup code needed
 */

import type { R2Bucket } from "@cloudflare/workers-types";

/**
 * Upload raw transcript text to R2 bucket
 *
 * File path: `transcripts/{videoId}.txt`
 * Content-Type: `text/plain; charset=utf-8`
 * TTL: 24 hours (via lifecycle rule, not customMetadata)
 *
 * @param bucket - R2 bucket binding (R2_TRANSCRIPTS)
 * @param videoId - YouTube video ID (e.g., "dQw4w9WgXcQ")
 * @param rawTranscript - Raw transcript text (no timestamps)
 * @returns Promise<void>
 *
 * @example
 * ```typescript
 * await uploadTranscriptToR2(
 *   env.R2_TRANSCRIPTS,
 *   "dQw4w9WgXcQ",
 *   "This is the raw transcript text..."
 * );
 * ```
 */
export async function uploadTranscriptToR2(
    bucket: R2Bucket,
    videoId: string,
    rawTranscript: string
): Promise<void> {
    const key = `transcripts/${videoId}.txt`;

    console.log(`[R2] Uploading transcript: ${key} (${rawTranscript.length} bytes)`);

    try {
        await bucket.put(key, rawTranscript, {
            httpMetadata: {
                contentType: "text/plain; charset=utf-8",
            },
            customMetadata: {
                videoId,
                uploadedAt: new Date().toISOString(),
                source: "youtube-transcript-mcp",
            },
        });

        console.log(`[R2] ✓ Upload successful: ${key}`);
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        console.error(`[R2] ✗ Upload failed: ${message}`);
        throw new Error(`R2 upload failed: ${message}`);
    }
}

/**
 * Generate public R2 URL for a transcript file
 *
 * Uses R2.dev subdomain for public access (no custom domain needed).
 * URL format: `https://pub-{hash}.r2.dev/transcripts/{videoId}.txt`
 *
 * Note: R2 public bucket URLs are automatically generated by Cloudflare.
 * The exact subdomain depends on your account configuration.
 *
 * @param bucketName - R2 bucket name (e.g., "youtube-transcripts")
 * @param videoId - YouTube video ID
 * @returns Public HTTPS URL to the transcript file
 *
 * @example
 * ```typescript
 * const url = getR2PublicUrl("youtube-transcripts", "dQw4w9WgXcQ");
 * // Returns: "https://pub-xxx.r2.dev/transcripts/dQw4w9WgXcQ.txt"
 * ```
 */
export function getR2PublicUrl(bucketName: string, videoId: string): string {
    // R2 public URLs use the bucket's public endpoint
    // Format: https://{bucket-name}.{account-id}.r2.cloudflarestorage.com/{key}
    //
    // However, for production use, you should configure a custom domain
    // in the R2 dashboard for cleaner URLs and better control.
    //
    // For now, we'll use the R2.dev subdomain pattern (requires public bucket).
    // If your bucket isn't public, you'll need to use Workers to proxy access.

    const key = `transcripts/${videoId}.txt`;

    // Simple approach: Return the key path
    // The Worker will need to serve this via a custom route or use R2.dev domain
    // For MVP, we'll construct a placeholder that assumes R2.dev public domain

    // TODO: Update this with your actual R2 public domain once configured
    // Option 1: R2.dev subdomain (if bucket is public)
    // Option 2: Custom domain (e.g., cdn.wtyczki.ai/transcripts/{videoId}.txt)
    // Option 3: Worker proxy route (e.g., /transcripts/{videoId})

    // For now, return a worker-proxied URL
    return `/r2/transcripts/${videoId}.txt`;
}

/**
 * Check if a transcript file exists in R2
 *
 * Useful for cache validation and debugging.
 *
 * @param bucket - R2 bucket binding
 * @param videoId - YouTube video ID
 * @returns True if file exists, false otherwise
 */
export async function transcriptExistsInR2(
    bucket: R2Bucket,
    videoId: string
): Promise<boolean> {
    const key = `transcripts/${videoId}.txt`;

    try {
        const object = await bucket.head(key);
        return object !== null;
    } catch (error) {
        console.error(`[R2] Error checking existence: ${error}`);
        return false;
    }
}

/**
 * Get transcript file from R2
 *
 * Used for debugging or manual retrieval.
 *
 * @param bucket - R2 bucket binding
 * @param videoId - YouTube video ID
 * @returns Transcript text or null if not found
 */
export async function getTranscriptFromR2(
    bucket: R2Bucket,
    videoId: string
): Promise<string | null> {
    const key = `transcripts/${videoId}.txt`;

    try {
        const object = await bucket.get(key);
        if (!object) {
            console.log(`[R2] File not found: ${key}`);
            return null;
        }

        const text = await object.text();
        console.log(`[R2] Retrieved transcript: ${key} (${text.length} bytes)`);
        return text;
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        console.error(`[R2] Error retrieving file: ${message}`);
        return null;
    }
}
